[package]
name = "sspss"
version = "0.1.0"
authors = ["Arne Dußin <arne.dussin@live.de>"]
edition = "2018"

[dependencies]
rust-crypto = "^0.2"
zeroize = "^1.0"

[features]
default = ["zeroize_derive"]
zeroize_derive = ["zeroize/zeroize_derive"]
